name: Check code with eslint

on:
    pull_request:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: "16.14.2"
            - name: Next Build Test
              run: yarn build
